services:
  express-app:
    image: backend-server-image-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    container_name: backend-server-container-prod
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ts-project
      - PGDATA=/var/lib/postgresql/data/pgdata/
    ports:
      - "5431:5432"
    # command: command
    volumes:
      - ./sql/db:/var/lib/postgresql/data/pgdata/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: sql-db